export const Settings = {
  GAME_WIDTH: 500,
  GAME_HEIGHT: 500,
  LARGE_ASTEROID_RADIUS: 40,
  MEDIUM_ASTEROID_RADIUS: 25,
  SMALL_ASTEROID_RADIUS: 15,
  PLAYER_RADIUS: 6,
  PROJECTILE_TTL: 200,
  PLAYER_SAFETY_RADIUS: 200,
  MIN_ASTEROID_VELOCITY: 1,
  ASTEROID_DIFFICULTY_VELOCITY_RATIO: 1,

}